sonar.projectKey=notes-app
sonar.projectName=Notes App
sonar.sources=client/src,server
sonar.tests=client/src/__tests__
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.svg,**/*.gif